# Add github config change label to any change of files in docs folder, or subfolders
github-config-change:
    - ".github/**/*"
    - ".pre-commit-config.yaml"
    - ".gitignore"

# Add code change label to any change of files ending with tf
code-change:
    - "*.tf"
    - "**/*.tf"
