default_stages: [commit]
fail_fast: false
default_language_version:
    python: python3.10

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0 # Use the ref you want to point at
      hooks:
          - id: check-added-large-files
          - id: check-ast
          - id: check-json
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: detect-private-key
          - id: fix-encoding-pragma
          - id: forbid-new-submodules
          - id: name-tests-test
          - id: check-toml
          - id: fix-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: debug-statements
          - id: detect-aws-credentials
            args: [--allow-missing-credentials]
          - id: detect-private-key
          - id: mixed-line-ending

    - repo: https://github.com/python-poetry/poetry
      rev: 1.7.0
      hooks:
        - id: poetry-check

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.14
      hooks:
        - id: ruff
          args: [--fix, --exit-non-zero-on-fix]

    - repo: https://github.com/codespell-project/codespell
      rev: v2.2.6
      hooks:
        - id: codespell
          args: [--check-filenames]
          additional_dependencies:
            - tomli

    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.27.3
      hooks:
          - id: check-github-workflows

    - repo: https://github.com/RobertCraigie/pyright-python
      rev: v1.1.348
      hooks:
      - id: pyright
        # args: [--verbose]

    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.85.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
      hooks:
          - id: tfupdate
            name: Autoupdate Terraform versions
          - id: terraform_checkov
            files: ^terraform/
            args:
                - --args=--quiet
                - --args=--skip-check CKV2_AWS_8
          - id: terraform_docs
            files: ^terraform/
            args:
                - --hook-config=--path-to-file=README.md
                - --hook-config=--add-to-existing-file=true
                - --hook-config=--create-file-if-not-exist=false
          - id: terraform_validate
            files: ^terraform/
            args:
                - --hook-config=--retry-once-with-cleanup=true
                - --tf-init-args=-upgrade
          - id: terraform_providers_lock
            files: ^terraform/
            args:
                - --hook-config=--mode=always-regenerate-lockfile
          - id: terraform_tflint
            files: ^terraform/
            args:
                - --hook-config=--delegate-chdir
          - id: terraform_trivy
            files: ^terraform/

    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 2.3.5
      hooks:
        - id: sqlfluff-lint
          additional_dependencies: ['dbt-athena-community==1.7.0', 'dbt-trino==1.7.1', 'sqlfluff-templater-dbt']

        - id: sqlfluff-fix
          additional_dependencies: ['dbt-athena-community==1.7.0', 'dbt-trino==1.7.1', 'sqlfluff-templater-dbt']
