default_stages: [commit]
fail_fast: false
default_language_version:
    python: python3.10

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0 # Use the ref you want to point at
      hooks:
          - id: check-added-large-files
          - id: check-ast
          - id: check-json
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: detect-private-key
          - id: fix-encoding-pragma
          - id: forbid-new-submodules
          - id: name-tests-test
          - id: check-toml
          - id: fix-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: debug-statements
          - id: detect-aws-credentials
            args: [--allow-missing-credentials]
          - id: detect-private-key
          - id: mixed-line-ending

    # GitHub Action Checks

    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: 0.27.3
      hooks:
          - id: check-github-workflows

    - repo: https://github.com/asottile/blacken-docs
      rev: 1.16.0
      hooks:
          - id: blacken-docs
            additional_dependencies: [black==23.12.0]
    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 23.12.0
      hooks:
          - id: black-jupyter
            language_version: python3.11
    - repo: https://github.com/timothycrosley/isort
      rev: 5.13.2
      hooks:
          - id: isort
    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-bugbear
                - flake8-comprehensions
                - flake8-simplify
            exclude: ^src/blib2to3
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.7.1
      hooks:
          - id: mypy
            exclude: ^docs/conf.py
            args: ["--config-file", "pyproject.toml"]
            additional_dependencies:
                - types-PyYAML
                - tomli >= 0.2.6, < 2.0.0
                - click >= 8.1.0, != 8.1.4, != 8.1.5
                - packaging >= 22.0
                - platformdirs >= 2.1.0
                - pytest
                - hypothesis
                - aiohttp >= 3.7.4
                - types-commonmark
                - urllib3
    #  TODO wait for working version
    # - repo: https://github.com/pre-commit/mirrors-prettier
    #   rev: v4.0.0-alpha.7
    #   files: ^terraform/
    #   hooks:
    #       - id: prettier
    #         entry: env PRETTIER_LEGACY_CLI=1 prettier

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.56.0
      hooks:
          - id: eslint
            args: [--fix]
            additional_dependencies:
                - eslint@latest
                - eslint-config-google@latest
                - eslint-config-prettier

    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.85.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
      hooks:
          - id: tfupdate
            name: Autoupdate Terraform versions
          - id: terraform_checkov
            files: ^terraform/
            args:
                - --args=--quiet
                - --args=--skip-check CKV2_AWS_8
          - id: terraform_docs
            files: ^terraform/
            args:
                - --hook-config=--path-to-file=README.md
                - --hook-config=--add-to-existing-file=true
                - --hook-config=--create-file-if-not-exist=false
          - id: terraform_validate
            files: ^terraform/
            args:
                - --hook-config=--retry-once-with-cleanup=true
                - --tf-init-args=-upgrade
          - id: terraform_providers_lock
            files: ^terraform/
            args:
                - --hook-config=--mode=always-regenerate-lockfile
          - id: terraform_tflint
            files: ^terraform/
            args:
                - --hook-config=--delegate-chdir
          - id: terraform_trivy
            files: ^terraform/

    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 2.3.5
      hooks:
        - id: sqlfluff-lint
          additional_dependencies: ['dbt-athena-community==1.7.0', 'dbt-trino==1.7.1', 'sqlfluff-templater-dbt']

        - id: sqlfluff-fix
          additional_dependencies: ['dbt-athena-community==1.7.0', 'dbt-trino==1.7.1', 'sqlfluff-templater-dbt']
          