version: "3"

dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

tasks:
    docker_login:
        preconditions:
            - test {{.GITHUB_TOKEN}}
            - test {{.GITHUB_USERNAME}}
        cmds:
            - echo "{{.GITHUB_TOKEN}}" | docker login ghcr.io -u {{.GITHUB_USERNAME}}
              --password-stdin

    docker_pull:
        cmds:
            - docker pull ghcr.io/pixie79/devcontainer:latest

    trivy:
        cmds:
            - trivy fs --scanners vuln,secret,config -f json terraform/

    jfrog_login:
        cmds:
            - terraform login projectolympus.jfrog.io

    tfinit_clean:
        dir: "terraform"
        cmds:
            - rm -rf .terraform

    tfinit:
        dir: "terraform"
        deps:
            - tfinit_clean
        cmds:
            - terraform init -backend=false

    tfvalidate:
        dir: "terraform"
        deps:
            - tfinit
        cmds:
            - terraform validate

    tflint:
        dir: "terraform"
        cmds:
            - tflint --recursive --color

    tflint_fix:
        dir: "terraform"
        cmds:
            - tflint --recursive --color --fix

    tfformat:
        dir: "terraform"
        cmds:
            - terraform fmt --recursive

    tfdocs:
        cmds:
            - terraform-docs terraform/

    tfcommit:
        deps:
            - tfvalidate
            - tflint
            - tfformat
            - tfdocs
        cmds:
            - git add .

    tfinit_remote_int:
        deps:
            - tfinit_clean
        dir: "terraform"
        cmds:
            - terraform init -input=false -backend-config=./backend_config/int-data.tfvars

    tfinit_remote_e2e:
        deps:
            - tfinit_clean
        dir: "terraform"
        cmds:
            - terraform init -input=false -backend-config=./backend_config/e2e-data.tfvars
