name: Smoke test "devcontainer" build

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    paths:
      - src/image/**
      - .github/devcontainer/smoke-devcontainer.yaml
      - .github/actions/**
      - build/**
jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
    - name: Smoke test
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        image: image
